name: kv-audio
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - kv-audio-net
  api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./Backend/.env 
    volumes:
      - ./Backend:/app
      - /app/node_modules
    networks:
      - kv-audio-net
    ports:
      - 3000:3000
    depends_on:
      - mongo
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    
    networks:
      - kv-audio-net
    ports:
      - 5173:5173
    command: npm run dev -- --host 
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

    depends_on:
      - api



    
volumes:
  mongo_data:
    

networks:
  kv-audio-net:
    driver: bridge
  


